[package]
name = "telecho"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atty = "0.2.14"
regex = "1.10.2"
strip-ansi-escapes = "0.2.0"
